version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    working_directory: /build/
    steps:
      - checkout
      - run:
          name: Create Resource.resx file
          command: |
            pushd ./LeaderBot/
            echo $RESOURCES_CS_FILE >> Resources.Designer.cs
            echo $RESOURCES_FILE >> Resources.resx
            ls -al
            popd
      - run:
          name: Moving to the project directory
          command: |
            pushd ./LeaderBot/
            dotnet publish -c Release -o /build/out
            popd
      - run:
          name: Run result
          command: dotnet out/LeaderBot.dll
