version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    working_directory: /build/
    steps:
      - checkout
      - run:
          name: Create Resource.resx file
          command: |
            pushd ./LeaderBot/
            echo $DATABASEUTILSLOCAL >> Utils/DatabaseUtilsLocal.cs
            popd
      - run:
          name: Build Project
          command: |
            pushd ./LeaderBot/
            dotnet publish -c Release -o /build/out
            popd
