name: Build .NET Core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Build with dotnet
      run: dotnet build -c Debug
    - uses: actions/setup-ruby@v1
    - name: Send Webhook Notification
      if: always()
      env:
        JOB_STATUS: ${{ job.status }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        HOOK_OS_NAME: ${{ runner.os }}
        WORKFLOW_NAME: ${{ github.workflow }}
        WEBHOOK_REPO: ${{ secrets.WEBHOOK_REPO }}
      run: |
        echo Status: $JOB_STATUS
        git clone $WEBHOOK_REPO webhook
        bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
      shell: bash